# Note: This file is tracked in git, so no sensitive info should be in here.
# These files are safe to be committed, see:
# https://github.com/cloudflare/wrangler/issues/209#issuecomment-541654484

name = "sables-dev-staging"
main = "dist/worker/entry-worker.js"

compatibility_date = "2022-11-13"
usage_model = "bundled"
compatibility_flags = [
  "streams_enable_constructors",
]

# Enabled, because Redux Toolkit requires that `global` be available.
node_compat = true

[triggers]
crons = [ ]

[vars]
ASSET_PROXY_URL = "http://localhost:8080/"

[env.production]
name = "sables-dev"

routes = [
  { pattern = "sables.dev", custom_domain = true, zone_name = "sables.dev" }
]

r2_buckets = [
  { binding = "SABLES_WEBSITE_ASSETS", bucket_name = "sables-dev", preview_bucket_name = "" }
]

[env.production.vars]
ASSET_PROXY_R2_BUCKET = "SABLES_WEBSITE_ASSETS"
